# Generated by Django 2.0.7 on 2019-11-27 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='people',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='First Name', max_length=20)),
                ('last_name', models.CharField(help_text='Last Name', max_length=20)),
            ],
        ),
    ]
